<?php
/**
 * @package Xlii_Configurator
 */
?>
    <div id="wrapper">
      <div class="trigger">
        <a id="openButton" class="button">Configure Product</a>
      </div>
      <div id="popup">
        <div id="close" class="hidden">X</div>
        <header class="header">
          <h1 class="title">
            Stel samen - EKI 400
          </h1>
          <h1 class="title-big">
            Stel samen - EKI 400
          </h1>
          <h2 class="subtitle">
            EPDM celrubber
          </h2>
          <p class="description">
            Donec ullamcorper nulla non metus auctor fringilla. Sed posuere
            consectetur est at lobortis. Nullam id dolor id nibh ultricies
            vehicula ut id elit. Sed posuere consectetur est at lobortis.
          </p>
        </header>

        <eki-product-configurator
          product-number="1300"
          locale="en"
          show-result
          debuggable
        >
          <div class="enquiries" slot="aside">
            <p class="note">
              Maat niet gevonden? Onze experts staan klaar om direct te helpen.
            </p>

            <div class="contact-card">
              <div class="contact">
                <p class="phone">
                  031 24 3773378
                </p>

                <p class="hours">
                  Maandag - vrijdag: 7.00 - 20.00 uur
                </p>
              </div>
              <div class="avatar">
                <img src="/images/avatar.png" alt="Contact person's avatar" />
              </div>
            </div>
          </div>
        </eki-product-configurator>
      </div>
    </div>
    <script>
      const demoEventElement = document.getElementsByTagName(
        "eki-product-configurator"
      )[0];
      demoEventElement.addEventListener("add-to-cart", async event => {
        console.info("[Event]", event.detail[0]);

        // NOTE: Below is just an example, should be done on server side
        try {
          const response = await fetch(
            "https://22jewafol1.execute-api.eu-central-1.amazonaws.com/dev/verifications",
            {
              method: "POST",
              headers: {
                "Content-Type": "application/json"
              },
              body: JSON.stringify(event.detail[0])
            }
          );
          if (response.ok) {
            let json = await response.json();
            console.log("verified:", result);
          } else {
            alert("HTTP-Error: " + response.status);
          }
        } catch (e) {
          console.error(e);
        }
      });
      demoEventElement.addEventListener("request-for-proposal", event => {
        console.info("[Event]", event.detail[0]);
      });
      demoEventElement.addEventListener("add-to-favorite", event => {
        console.info("[Event]", event.detail[0]);
      });
    </script>
   
    <script>
      $(document).ready(function() {
        $("#openButton").click(function() {
          $("#popup")
            .addClass("overlay")
            .fadeIn(300);
          $("#close")
            .removeClass("hidden")
            .addClass("close");
        });

        $("#close").click(function() {
          $("#popup")
            .removeClass("overlay")
            .fadeOut(300, function() {
              $("#popup").removeAttr("style")
            })
          $(this)
            .removeClass("close")
            .addClass("hidden");
        });
      });
    </script>
