<div>
    <label class="label" for="companyname">
      <span><?= $block->escapeHtml(__('Company Name')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="companyname" id="companyname" value="" title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>">
    </div>
    <label class="label" for="vatnumber">
      <span><?= $block->escapeHtml(__('VAT Number')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="vatnumber" id="vatnumber" value="" title="<?= $block->escapeHtmlAttr(__('VAT Number')) ?>">
    </div>
    <label class="label" for="kvknumber">
      <span><?= $block->escapeHtml(__('KVK Number')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="kvknumber" id="kvknumber" value="" title="<?= $block->escapeHtmlAttr(__('KVK Number')) ?>">
    </div>
</div>
