<?php
    $collections = $this->getFaqProductCollection();
?>
<legend class="legend"><h2><span><?php echo $block->escapeHtml(__('FAQ Page')) ?></span></h2></legend><br />
 <?php foreach ($collections as $key => $data): ?>

 <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span><h4>-&nbsp;<?php echo $data->getQuestion(); ?></h4></span>
        </div>
    </div>
    <div data-role="content">&nbsp;&nbsp;<strong>Ans:</strong>&nbsp;<?php echo $data->getAnswer(); ?></div>
</div>
<?php endforeach; ?>
